/**
 * Common Type Definitions for Maharashtra Water Billing System
 */

export type Language = 'en' | 'mr';

export type MainTab = 'reports' | 'sms';

export type EngineTab = 'reports' | 'data';

export type SubTab = 'engine' | 'collection' | 'crm' | 'quick';

export interface AutoReportNotification {
  isOpen: boolean;
  reportName: string;
  reportType: string;
}

export interface DailyReportPattern {
  reportType: string;
  reportName: string;
  filters: Record<string, any>;
  lastGenerated?: number;
}

export interface ReportHistory {
  reportType: string;
  reportName: string;
  timestamp: number;
  filters?: Record<string, any>;
  autoGenerated?: boolean;
  exportedAt?: number;
}

export interface UserInfo {
  name: string;
  role: string;
  email?: string;
  department?: string;
}

export interface SearchResult {
  id: string;
  title: string;
  description: string;
  category: string;
  relevance: number;
}
